name: Run Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Ejecuta cada 5 minutos

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Esto se ejecuta cada 5 minutos!"
